include:
  # Sweep standalone only — matching reference Sweep-Pro
  - board: nice_nano//zmk
    shield: sweep_left
  - board: nice_nano//zmk
    shield: sweep_right
  - board: nice_nano//zmk
    shield: settings_reset
