# Encoder sensor — needed on peripheral half for EC11 rotation to work
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# i2c
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

# pointing device
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_INPUT_THREAD_STACK_SIZE=4096

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y
